# Generated by Django 2.2.1 on 2019-07-17 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zbest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='portrait',
            field=models.ImageField(upload_to='portrait'),
        ),
    ]
