# Generated by Django 2.2.1 on 2019-07-18 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zbest', '0003_order_create_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='gender',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='account',
            name='nickname',
            field=models.CharField(default='匿名用户', max_length=30),
        ),
    ]
