# Generated by Django 2.2.1 on 2019-07-18 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zbest', '0004_auto_20190718_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='portrait',
            field=models.ImageField(upload_to='portrait/'),
        ),
    ]
