# Generated by Django 2.2.1 on 2019-07-18 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zbest', '0005_auto_20190718_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='gender',
            field=models.IntegerField(default=1),
        ),
    ]
