# Generated by Django 2.2.1 on 2019-07-18 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zbest', '0006_auto_20190718_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='gender',
            field=models.CharField(default=1, max_length=2),
        ),
    ]
