# Generated by Django 2.2.1 on 2019-07-04 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroinfo',
            name='gender',
            field=models.CharField(choices=[('m', '男'), ('w', '女')], max_length=10),
        ),
    ]
