# Generated by Django 2.2.1 on 2019-07-12 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190712_1949'),
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='auth',
            field=models.ForeignKey(default='admin', on_delete=django.db.models.deletion.CASCADE, to='blog.BlogUser'),
        ),
    ]
