# Generated by Django 2.2.1 on 2019-07-12 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_comment_auth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='auth',
        ),
    ]
